### ISSUE TITLE
bib2gls doesn't run under MiKTeX

### ISSUE THREAD

**Issue by 0x7fh** [nlct/bib2gls#1]
If I run `bib2gls` under MiKTeX, with or without command line option, it doesn't matter, it responds always with

    Fatal error: kpsewhich '--var-value=openin_any' failed with exit code 1

It's quite consistent in it's behavior 😄 

According to MiKTeX Package manager, it is version 1.0, packaged on 2017-09-13 22:01:57.

Btw, `convertgls2bib` works fine.

**Comment by nlct** [comment]
I'm currently working on version 1.1, so I'll see if I can get it fixed for the next release. The call to `kpsewhich` is part of the security settings to comply with TeX Live's requirements, but MikTeX doesn't use `openin_any`. `bib2gls` ought to fallback on `openin_any=a` if `kpsewhich` can't find a value, but it seems it's not doing this. `convertgls2bib` doesn't have this security feature, which is why it's unaffected.

**Comment by nlct** [comment]
I've uploaded version 1.1 to CTAN. It should now fall back on default settings if `openin_any` or `openout_any` aren't defined. It may take a few days for the new version to make it into the TeX distributions.

**Comment by 0x7fh** [comment]
Great. It runs great now under MixTeX.

**Comment by nlct** [comment]
Thank you for confirming :smiley:
