### ISSUE TITLE
bib2gls detects wrong encoding

### ISSUE THREAD

**Issue by Vasco-Da-Gama-png** [nlct/bib2gls#25]
I have a LaTeX Repo, which is compile with LuaLaTeX: https://collaborating.tuhh.de/m21/public/theses/itt-latex-template
Since bib2gls 3.5 I have issues, where bib2gls says, the encoding of the .aux-file would be US-ASCII.
Although when I open the file, it shows it is UTF-8 encoded. Any ideas, why this could be?

Excerpt of the compiler log:
```bib2gls 3.5 (2023-08-24)
Read
[latex_compiler.log](https://github.com/nlct/bib2gls/files/12499397/latex_compiler.log)
ing itt_vorlage.aux
Encoding: US-ASCII
Error: Can't parse itt_vorlage.aux: may not be UTF-8 encoded.
(Try a different encoding with --tex-encoding or --default-encoding.)
Transcript written to itt_vorlage.glg.```

**Comment by nlct** [comment]
The `latexmk` log file you provided only shows the minimal information `bib2gls` writes to stdout in non-verbose mode. The second line of the `.glg` file should start `Default encoding:` which will indicate your default encoding. However, `bib2gls` should pick up `fontspec` from the log file, which should switch it to UTF-8. The next line of the `.glg` file should say `Reading itt_vorlage.log`. If it doesn't then the log file isn't available.

I notice the `latexmk` log file contains the following before `bib2gls`:
```
No existing .aux file, so I'll make a simple one, and require run of *latex.
```
If there's no `aux` file and `latexmk` is creating a simple one and then running `bib2gls` before `lualatex` then there's no log file for `bib2gls` to detect `fontspec` and the `aux` file won't contain the necessary information for `bib2gls` to work, which is likely why it's also showing the error:
```
Error: Missing \glsxtr@resource in aux file. (Have you used \glsxtrresourcefile or \GlsXtrLoadResources?)
```

Try compiling directly (without `latexmk`):
```
lualatex itt_vorlage
bib2gls itt_vorlage
lualatex itt_vorlage
```
If the encoding is correct in this case and the missing `\glsxtr@resource` error has gone then the problem is with the `latexmk` rule running `bib2gls` before `lualatex`.

**Comment by Vasco-Da-Gama-png** [comment]
First of all, thanks for the fast answer!
What is interesting, is that with version 3.4 it works with latexmk and this order:

```bib2gls 3.4 (2023-06-29)
Reading itt_vorlage.aux
Reading bib/glossaries/abbreviations.bib
Encoding: UTF-8
Reading bib/glossaries/index/terms.bib
Encoding: UTF-8
Reading bib/glossaries/index/names.bib
Encoding: UTF-8
Reading bib/glossaries/symbols/roman.bib
Encoding: UTF-8
Reading bib/glossaries/symbols/greek.bib
Encoding: UTF-8
Reading bib/glossaries/symbols/other.bib
Encoding: UTF-8
Reading bib/glossaries/symbols/subscripts.bib
Encoding: UTF-8
Reading bib/glossaries/constants.bib
Encoding: UTF-8
Writing /workspaces/ITT LaTeX template/itt_vorlage.glstex
17 entries written to /workspaces/ITT LaTeX template/itt_vorlage.glstex.
Writing /workspaces/ITT LaTeX template/itt_vorlage-1.glstex
2 entries written to /workspaces/ITT LaTeX template/itt_vorlage-1.glstex.
Writing /workspaces/ITT LaTeX template/itt_vorlage-2.glstex
4 entries written to /workspaces/ITT LaTeX template/itt_vorlage-2.glstex.
Writing /workspaces/ITT LaTeX template/itt_vorlage-3.glstex
24 entries written to /workspaces/ITT LaTeX template/itt_vorlage-3.glstex.
Writing /workspaces/ITT LaTeX template/itt_vorlage-4.glstex
6 entries written to /workspaces/ITT LaTeX template/itt_vorlage-4.glstex.
Writing /workspaces/ITT LaTeX template/itt_vorlage-5.glstex
9 entries written to /workspaces/ITT LaTeX template/itt_vorlage-5.glstex.
Writing /workspaces/ITT LaTeX template/itt_vorlage-6.glstex
6 entries wri
[latex_compiler_bib2gls_v3.4.log](https://github.com/nlct/bib2gls/files/12499888/latex_compiler_bib2gls_v3.4.log)
tten to /workspaces/ITT LaTeX template/itt_vorlage-6.glstex.
Writing /workspaces/ITT LaTeX template/itt_vorlage-7.glstex
3 entries written to /workspaces/ITT LaTeX template/itt_vorlage-7.glstex.
71 entries written in total.```

So that's why I'm a bit confused and thought it might be a problem of version 3.5
Also the problem with the missing .aux file was just, because it was a run, where I personally deleted the .aux file before...
In the other attached file you can see, that it doesn't occur again.

**Comment by nlct** [comment]
The encoding related changes were introduced to v3.5 in response to issue #24. There wasn't enough information in the `glg` file to immediately diagnose the problem, so I added more logging (and a couple of extra switches). So v3.4 may well be reading the `aux` file as US-ASCII, without indicating this, and then switching to UTF-8 when it detects the encoding line in the `bib` files or because it's picked up `uft8` in the `aux` file.

The main encoding changes in v3.5 were to ensure that the default was picked up from `--default-encoding` if it was supplied rather than always falling back on the JVM default if no information about the encoding was found in any of the files (`log`, `aux`, and `bib`).

**Comment by nlct** [comment]
There are no error messages in the bit of the transcript you've provided. It's reporting information, which includes what file encoding `bib2gls` has been told to use. Try `--verbose` instead of `--debug`.

`bib2gls` doesn't try to detect the file encoding in the way that `file` does. This is because there is no 100% reliable way of detecting a file encoding (`file` mostly guesses), so `bib2gls` starts with the system default and follows instructions to override that default. So whilst `file` can correctly detect the encoding in this instance, `bib2gls` doesn't make the same guess, as there's a chance it could guess wrong (and it would mean repeatedly parsing the file, first to determine the encoding, and then to read the required information).

The line `Default encoding: US-ASCII` is reporting the default encoding, which means it's likely that the docker image has ASCII as the default encoding. Since you are using LuaLaTeX, you can test for this by adding the following line to your document:
```tex
{\catcode`\_11 Lang: \directlua{ tex.print( os.getenv("LANG") ) }.}
```
If that line in the PDF isn't in the form "Lang: _locale_.utf8" or "Lang: _locale_.UTF-8" then the Docker image doesn't have UTF-8 as the default encoding. I can't find anything in the [Dockerfile](https://collaborating.tuhh.de/m21/public/theses/latex_dockerfile/-/blob/master/Dockerfile) from the site you linked to that sets the encoding to UTF-8 in which case it's likely defaulting to POSIX and ASCII. The Dockerfile would need to have something like `ENV LANG C.UTF-8` to default to  UTF-8.

You mentioned using LuaLaTeX but the `glg` file indicates that `fontenc` has been loaded in the document. It's more usual to use `fontspec` with LuaLaTeX. If `bib2gls` had found `fontspec` it would have automatically switched to UTF-8 for the TeX files.

I suggest you run bib2gls with `--default-encoding UTF-8` if you are using docker.

**Comment by nlct** [comment]
I'm sorry I didn't notice the log files in your attached `zip` file were the `bib2gls` transcripts, which has the error:
```
Error: Can't parse itt_vorlage.aux: may not be UTF-8 encoded.
(Try a different encoding with --tex-encoding or --default-encoding.)
```

**Comment by nlct** [comment]
I think the error message has been messed up. I'll look into it, but try with `--default-encoding UTF-8` to see if it solves the problem.

**Comment by Vasco-Da-Gama-png** [comment]
So, with the option `--default-encoding UTF-8` it works with version 3.5.
But I do not really understand, why this error happens. Because the language of Debian is standard set to en_US.UTF-8 and checking that with:
```
tex@7a5436936e7f:/workspaces/ITT LaTeX template$ echo $LANG
en_US.UTF-8
tex@7a5436936e7f:/workspaces/ITT LaTeX template$ echo os.getenv("LANG")
bash: syntax error near unexpected token `('
tex@7a5436936e7f:/workspaces/ITT LaTeX template$ dpkg -l locales
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
un  locales        <none>       <none>       (no description available)
tex@7a5436936e7f:/workspaces/ITT LaTeX template$ locale 
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=POSIX
tex@7a5436936e7f:/workspaces/ITT LaTeX template$ 
```
It also shows, that this is set correct. Adding that line that you recommended in the Dockerfile (I just tried using the latest image as base image and adding that line) also didn't change anything but changing en_US to C:
```
tex@29994a8f9cf9:/workspaces/ITT LaTeX template$ echo $LANG
C.UTF-8
tex@29994a8f9cf9:/workspaces/ITT LaTeX template$ locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=POSIX
```

**Comment by nlct** [comment]
> Because the language of Debian is standard set to en_US.UTF-8

This isn't necessarily the case with Debian Docker images.

The next version of `bib2gls` will have better error handling for encoding mismatches, but the problem here is that the Docker image is POSIX and defaulting to ASCII.

If `C` isn't supported in the locale, the Dockerfile probably needs:
```
ENV LANGUAGE en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
```

**Comment by Vasco-Da-Gama-png** [comment]
I think I start to understand the problem, but I don't know how to fix it...

```
tex@7b5be72746f9:/workspaces/ITT LaTeX template$ locale
LANG=C.utf8
LANGUAGE=C.utf8
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=POSIX
tex@7b5be72746f9:/workspaces/ITT LaTeX template$ locale -a
C
C.utf8
POSIX
tex@7b5be72746f9:/workspaces/ITT LaTeX template$ locale charmap
ANSI_X3.4-1968
```
I googled around a lot, but I found nothing on how to fix this. Adding what you suggested didn't help and adding
```
ENV LANGUAGE C.utf8
ENV LANG C.utf8
ENV LC_ALL C.utf8
```
Also didn't work. I thought that the problem might be, that en_US.UTF-8 isn't installed.
Do you have any idea what the problem could be an how to fix it?

**Comment by nlct** [comment]
I've fixed the problem with `bib2gls` terminating when it encounters a mismatched encoding (v3.6) which I've just uploaded to CTAN. That should mean that it will retry if it's incorrect. It will take a few days before it reaches the TeX distributions.

For your Docker problem, maybe [How to set the locale inside a Debian/Ubuntu Docker container?](https://stackoverflow.com/questions/28405902) might help.

**Comment by Vasco-Da-Gama-png** [comment]
So, finally I found my mistake, but updating bib2gls itself might be also a good idea.

```
ENV LANG C.utf8
ENV LC_ALL C.utf8
```

with adding locales to be installed in the image work for setting the right encoding. The only problem was, that I'm using this image with VSC and the devcontainer package. And in the devcontainer.json there was this block:

```
    "containerEnv": {
        "LC_ALL": "POSIX"
    }
}
```
which always changed the encoding to POSIX and ASCI within VSC. So I now added the right encoding in the Docker image itself and now don't need the line `"LC_ALL": "POSIX"` in the devcontainer.json anymore.
Thanks a lot for your help and input!

**Comment by nlct** [comment]
It's good that you've got the Docker settings fixed. Your issue helped me to discover a bug in the handling of `--default-encoding` where the system default was still being used, and also `bib2gls` will now retry parsing the `aux` file if it encounters a contradictory encoding in `\glsxtr@texencoding`.

**Comment by Vasco-Da-Gama-png** [comment]
Close
