### ISSUE TITLE
Bib2gls support for UTF-8: .glstex cant read non-ASCII characters from .bib file without charset=UTF-8 while using luaLaTeX or XeLaTeX

### ISSUE THREAD

**Issue by Delanii** [nlct/bib2gls#5]
Hello,

I found bib2gls functionality, that could be regarded as bug (if it is not intentional). 

My native language is czech. If I use my language non-ASCII characters, such as:

"ěščřžýáíéďťň"

these characters cannot be transferred from .bib file to generated .glstex file, until I use \GlsXtrLoadResources option "charset=UTF-8." Is that intended? 

Regarding to Ms. Ulrike Fischer from TeX Stack Exchange, the bib2gls should be able to automatically detect UTF-8 characters. For further compilation, I was using LuaLaTeX a XeLaTeX, which both displayed same issue. LuaLaTeX is then unable to do the second compilation run, XeLaTeX shows wrong characters/glyphs.

I am making this report based on suggestion from Ms. Ulrike Fischer from TeX Stack Exchange. Here is the link to my original question/issue on TeX Stack Exchange:

https://tex.stackexchange.com/questions/489595/bib2gls-support-for-non-ascii-characters-or-non-english-languages-glstex-is-un/489922#489922

In attachment I am sending .tex file (in .txt format) set to XeLaTeX compilation with arara displaying my issue, with commented line 33, with setting of the option charset = UTF-8 and .pdf produced.
[TestBib2gls.txt](https://github.com/nlct/bib2gls/files/3161273/TestBib2gls.txt)
[TestBib2gls.pdf](https://github.com/nlct/bib2gls/files/3161274/TestBib2gls.pdf)

**Comment by nlct** [comment]
The encoding comment in your `.bib` file is incorrect. It should be:

    % Encoding: UTF-8

If this is missing (and the `charset` option hasn't been used), then bib2gls will fall back on the default file encoding for your Java virtual machine. This just covers the encoding for the `.bib` files.

The encoding for the `.glstex` files is obtained from the `.aux` file, but this is only set if `glossaries-extra.sty` can work out the document encoding, which is obtained from `\inputencodingname` if it's defined otherwise if `fontspec` has been loaded the value is assumed to be `utf8`. If the encoding hasn't been written to the `.aux` file then the encoding defaults to the `file.encoding` setting used by the Java virtual machine. The `--tex-encoding` can be used to override this.

Both the `.bib` and `.glstex` encodings need to be correctly set for the characters to be correctly written to match the `.tex` document. Without the `% Encoding:` comment in the `.bib` file and without `inputenc`/`fontspec` in the document, the default Java file encoding will be assumed for both. 

Your example document includes `fontspec`, so the following line appears in the `.aux` file:

    \glsxtr@texencoding{utf8}

The `.glg` file shows

    TeX character encoding: UTF-8

which means that bib2gls has correctly obtained the TeX encoding from the `.aux` file.

The `.bib` file doesn't have the encoding set because there's a mistake in the comment line:

    % Encoding = UTF-8

This should be 

    % Encoding: UTF-8

This means that bib2gls doesn't detect the encoding. Since `charset` isn't set, bib2gls falls back on the Java default. My Java installation is set up to use UTF-8 by default, so that's what's used, so your example works fine for me. I'm guessing that your version of Java has a different value for the `file.encoding` property. However, the correct solution is to fix the encoding comment line (although you might also want to look into changing the `file.encoding` property if you want all Java applications to default to UTF-8).
