### ISSUE TITLE
pgls without gls fails

### ISSUE THREAD

**Issue by larseggert** [nlct/bib2gls#7]
Not sure if this is the right repo to file this in, but when I use `\pgls` in a document without also using `\gls` for the same term somewhere, the entry is always undefined.

**Comment by nlct** [comment]
It's a problem with `glossaries-extra` rather than `bib2gls`. It looks like `\pgls` isn't writing the record information in the `.aux` file. I've also opened [an issue on the `glossaries-extra` bug tracker](https://dickimaw-books.com/bugtracker.php?action=view&key=139).

**Comment by nlct** [comment]
It turns out the actual problem is in `glossaries-prefix.sty` rather than `glossaries-extra.sty`. I've now fixed the issue in `glossaries-prefix.sty` version 4.44 (2019-12-06), so you will need to update the base `glossaries` package to ensure that `\pgls` works with `bib2gls`. It may take a few days for the new version to make it into the TeX distributions.
