### ISSUE TITLE
Encoding when using bib2gls on Windows 10

### ISSUE THREAD

**Issue by psgh** [nlct/bib2gls#8]
Hello,

When using bib2gls on Windows 10 1909 bib2gls does not correcly recognize UTF-8 characters. Compiling the same files on Linux(Ubuntu 18.04 LTS in my case) or WSL produces expected output. Please see attached example files.
[document_linux.pdf](https://github.com/nlct/bib2gls/files/3893109/document_linux.pdf)
[document_windows.pdf](https://github.com/nlct/bib2gls/files/3893110/document_windows.pdf)
[document.tex.txt](https://github.com/nlct/bib2gls/files/3893118/document.tex.txt)
[glossary.bib.txt](https://github.com/nlct/bib2gls/files/3893119/glossary.bib.txt)
 Renamed the last two files with .txt endings as github does not allow to attach them with the original endings.

**Comment by nlct** [comment]
Does the `.glg` file contain the following on line 3:
```
TeX character encoding: UTF-8
```
There should also be some other encoding lines in the transcript. The encoding line following `Reading /path/to/something.bib` indicates the (input) file encoding of the `.bib` file (which should be UTF-8 since you have that encoding set in the `.bib` file). The encoding line following `Writing /path/to/something.glstex` indicates the (output) file encoding of the `.glstex` file. This should be `UTF-8` because you've used `fontspec`. There should be also be the following line in the `.aux` file:
```latex
\glsxtr@texencoding{utf8}
```
My guess is that one of these encoding specifications is incorrect on your Windows device. Can you check the `.glg` and `.aux` files to find out which one is wrong?

**Comment by psgh** [comment]
Due to some compatibility issues I am running an older version of texlive which contains bib2gls version 1.4 . After downloading a newer version of bib2gls from CTAN(or running the older version jar directly with -Dfile.encoding=UTF-8 option) my encoding issue was resolved, everything works correctly.
